<?xml version="1.0" encoding="UTF-8"?>
<Program Stored="true" Version="1.0">
  <!--ProgramListConv version: 1.1. Conversion date: 2014-06-24. Done by: max.-->
  <ProgramType>0</ProgramType>
  <MenuGroup>2</MenuGroup>
  <IsFavorite>false</IsFavorite>
  <Image Image="153_Schweinshaxe.jpg" ImgWide="true" />
  <StepList>
    <Step>
      <StepType>1</StepType>
      <Duration>1800.0</Duration>
      <Temperature>99.0</Temperature>
      <HumidityPercentage>100</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <PhaseThroughTime>0</PhaseThroughTime>
      <HumidityAmount>0</HumidityAmount>
      <HumidityAmountType>0</HumidityAmountType>
      <PhaseHumidityTime>0</PhaseHumidityTime>
      <PhaseRestingTime>0</PhaseRestingTime>
    </Step>
    <Step>
      <StepType>0</StepType>
      <Duration>0.0</Duration>
      <Temperature>140.0</Temperature>
      <HumidityPercentage>40</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <PhaseThroughTime>0</PhaseThroughTime>
      <HumidityAmount>0</HumidityAmount>
      <HumidityAmountType>0</HumidityAmountType>
      <PhaseHumidityTime>0</PhaseHumidityTime>
      <CoreTemperature>74.0</CoreTemperature>
      <PhaseRestingTime>0</PhaseRestingTime>
      <BusFanSpeed>5</BusFanSpeed>
    </Step>
    <Step>
      <StepType>2</StepType>
      <Duration>900.0</Duration>
      <Temperature>220.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
  </StepList>
  <PreheatActive>true</PreheatActive>
  <PreheatTemp>108.9</PreheatTemp>
  <BuilderDevice>0</BuilderDevice>
  <Comment>Accessories:
Grid 
Briefly steam the knuckle of pork, then score and salt. 
Insert the core probe.
Insert grease drip tray underneath as required.</Comment>
</Program>