<?xml version="1.0" encoding="utf-8"?>
<Program Version="1.0" Stored="true">
  <ProgramType>0</ProgramType>
  <IsFavorite>false</IsFavorite>
  <MenuGroup>2</MenuGroup>
  <Image Image="149_Schweinebaeckchen.jpg" ImgWide="true" />
  <PreheatActive>false</PreheatActive>
  <PreheatTemp>0.0</PreheatTemp>
  <SPSActive>false</SPSActive>
  <HalfLoad>false</HalfLoad>
  <KeepWarm>false</KeepWarm>
  <ReducedHeatOutput>false</ReducedHeatOutput>
  <CleaningCoolingType>0</CleaningCoolingType>
  <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
  <CleaningStartupCheckTemp>0.0</CleaningStartupCheckTemp>
  <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
  <StepList>
    <Step>
      <StepType>4</StepType>
      <Duration>0.0</Duration>
      <Temperature>20.0</Temperature>
      <HumidityPercentage>99</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>1</FanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>60.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
      </Cleaning>
    </Step>
    <Step>
      <StepType>0</StepType>
      <Duration>0.0</Duration>
      <Temperature>72.0</Temperature>
      <HumidityPercentage>20</HumidityPercentage>
      <FanMode>3</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>72.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
      </Cleaning>
      <BusFanSpeed>4</BusFanSpeed>
    </Step>
  </StepList>
  <BuilderDevice>0</BuilderDevice>
  <Comment>Accessory: 
Container 100 mm

Sear pork cheeks, place in container, cover with liquid and insert core probe.
No holding phase!</Comment>
</Program>