<?xml version="1.0" encoding="UTF-8"?>
<Program Stored="true" Version="1.0">
  <!--ProgramListConv version: 1.1. Conversion date: 2014-06-24. Done by: max.-->
  <ProgramType>1</ProgramType>
  <MenuGroup>8</MenuGroup>
  <IsFavorite>false</IsFavorite>
  <Image Image="119_Plundergeb'195'145ck.jpg" ImgWide="true" />
  <StepList>
    <Step>
      <StepType>7</StepType>
      <Duration>1.0</Duration>
      <Temperature>140.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>true</ExhaustAirFlapClosed>
      <PhaseThroughTime>180</PhaseThroughTime>
      <HumidityAmount>200</HumidityAmount>
      <HumidityAmountType>0</HumidityAmountType>
      <PhaseHumidityTime>30</PhaseHumidityTime>
      <CoreTemperature>0.0</CoreTemperature>
      <PhaseRestingTime>40</PhaseRestingTime>
    </Step>
    <Step>
      <StepType>6</StepType>
      <Duration>1.0</Duration>
      <Temperature>175.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>true</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>840</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
    <Step>
      <StepType>6</StepType>
      <Duration>1.0</Duration>
      <Temperature>175.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>120</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
  </StepList>
  <Comment>Zubehör:
Backblech Alu mit KG-Flon,

Plunderteile formen oder TK
Plunderteile auf das Backblech setzen 
Alle Produkte direkt in den vorgeheizten Garraum geben.</Comment>
  <PreheatActive>true</PreheatActive>
  <PreheatTemp>154.0</PreheatTemp>
  <BuilderDevice>0</BuilderDevice>
</Program>