<?xml version="1.0" encoding="utf-8"?>
<Program Version="1.0" Stored="true">
  <ProgramType>1</ProgramType>
  <IsFavorite>true</IsFavorite>
  <MenuGroup>-1</MenuGroup>
  <BuilderDevice>0</BuilderDevice>
  <Image Image="Lasagne.jpg" ImgWide="true" />
  <BarcodeValue />
  <RestrictValue />
  <MultiDeltaT>false</MultiDeltaT>
  <PreheatActive>true</PreheatActive>
  <PreheatTemp>170.0</PreheatTemp>
  <SPSActive>false</SPSActive>
  <HalfLoad>false</HalfLoad>
  <KeepWarm>false</KeepWarm>
  <ReducedHeatOutput>false</ReducedHeatOutput>
  <CleaningCoolingType>0</CleaningCoolingType>
  <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
  <CleaningStartupCheckTemp>0.0</CleaningStartupCheckTemp>
  <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
  <StepList>
    <Step>
      <StepType>7</StepType>
      <Duration>1.0</Duration>
      <Temperature>140.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>4</BusFanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>true</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>150</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>30</PhaseHumidityTime>
        <PhaseRestingTime>40</PhaseRestingTime>
        <PhaseThroughTime>900</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
    <Step>
      <StepType>7</StepType>
      <Duration>1.0</Duration>
      <Temperature>140.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>5</BusFanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>true</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>100</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>30</PhaseHumidityTime>
        <PhaseRestingTime>40</PhaseRestingTime>
        <PhaseThroughTime>600</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
    <Step>
      <StepType>6</StepType>
      <Duration>1.0</Duration>
      <Temperature>170.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>5</BusFanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>900</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
  </StepList>
  <Comment>In der Aluschale gekühlt

Auf geschlossenen Blech garen
Nicht zu eng aneinander stellen</Comment>
</Program>