<?xml version="1.0" encoding="UTF-8"?>
<Program Stored="true" Version="1.0">
  <ProgramType>0</ProgramType>
  <IsFavorite>false</IsFavorite>
  <MenuGroup>3</MenuGroup>
  <Image Image="chicken roasted whole.jpg" ImgWide="true" />
  <Comment>Roast whole chickens directly on grid. insert probe in thickest part of the breast meat, avoid touching the bone with probe tip.
For chicken pieces isert probe into leg quarter</Comment>
  <PreheatActive>true</PreheatActive>
  <PreheatTemp>217.5</PreheatTemp>
  <SPSActive>false</SPSActive>
  <HalfLoad>false</HalfLoad>
  <KeepWarm>false</KeepWarm>
  <ReducedHeatOutput>false</ReducedHeatOutput>
  <CleaningCoolingType>0</CleaningCoolingType>
  <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
  <CleaningStartupCheckTemp>0</CleaningStartupCheckTemp>
  <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
  <StepList>
    <Step>
      <StepType>0</StepType>
      <Duration>0.0</Duration>
      <Temperature>196.111111111111</Temperature>
      <HumidityPercentage>20</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>60.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
      </Cleaning>
      <BusFanSpeed>5</BusFanSpeed>
    </Step>
    <Step>
      <StepType>2</StepType>
      <Duration>0.0</Duration>
      <Temperature>210.0</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>1</FanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>79.4444444444444</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
      </Cleaning>
      <BusFanSpeed>1</BusFanSpeed>
    </Step>
  </StepList>
  <BuilderDevice>1</BuilderDevice>
  <RecipeIndex>11</RecipeIndex>
  <ProconnectRecipeName>Chicken whole or pieces PROBE</ProconnectRecipeName>
</Program>