<?xml version="1.0" encoding="utf-8"?>
<Program Version="1.0" Stored="true">
  <ProgramType>0</ProgramType>
  <IsFavorite>false</IsFavorite>
  <MenuGroup>2</MenuGroup>
  <BuilderDevice>1</BuilderDevice>
  <Image Image="Pork-roast.jpg" ImgWide="true" />
  <Comment>insert probe in the center of roast.
For best results roast directly on wire shelf with drip pan below</Comment>
  <BarcodeValue />
  <RestrictValue />
  <MultiDeltaT>false</MultiDeltaT>
  <PreheatActive>true</PreheatActive>
  <PreheatTemp>165.555555555556</PreheatTemp>
  <SPSActive>false</SPSActive>
  <HalfLoad>false</HalfLoad>
  <KeepWarm>false</KeepWarm>
  <ReducedHeatOutput>false</ReducedHeatOutput>
  <CleaningCoolingType>0</CleaningCoolingType>
  <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
  <CleaningStartupCheckTemp>0.0</CleaningStartupCheckTemp>
  <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
  <StepList>
    <Step>
      <StepType>2</StepType>
      <Duration>300.0</Duration>
      <Temperature>148.888888888889</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>5</BusFanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>0.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
    <Step>
      <StepType>0</StepType>
      <Duration>0.0</Duration>
      <Temperature>121.111111111111</Temperature>
      <HumidityPercentage>15</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>3</BusFanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>60.0</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
  </StepList>
  <RecipeIndex>34</RecipeIndex>
  <ProconnectRecipeName>Pork loin roast</ProconnectRecipeName>
</Program>