<?xml version="1.0" encoding="UTF-8"?>
<Program Stored="true" Version="1.0">
    <!--ProgramListConv version: 1.1. Conversion date: 2014-06-24. Done by: max.-->
    <ProgramType>0</ProgramType>
    <Comment>ローストヒ゛ーフ</Comment>
    <Image Image="" ImgWide="true" />
    <StepList>
        <Step>
            <StepType>0</StepType>
            <Duration>600</Duration>
            <Temperature>160</Temperature>
            <HumidityPercentage>20</HumidityPercentage>
            <FanMode>4</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>false</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
        </Step>
        <Step>
            <StepType>3</StepType>
            <Duration>0</Duration>
            <Temperature>80</Temperature>
            <HumidityPercentage>30</HumidityPercentage>
            <FanMode>3</FanMode>
            <FanSpeed>5</FanSpeed>
            <IsCoreTempStep>true</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
            <Cooking>
                <CoreTemperature>50</CoreTemperature>
            </Cooking>
        </Step>
        <Step>
            <StepType>3</StepType>
            <Duration>0</Duration>
            <Temperature>57</Temperature>
            <HumidityPercentage>10</HumidityPercentage>
            <FanMode>3</FanMode>
            <FanSpeed>5</FanSpeed>
            <IsCoreTempStep>true</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
            <Cooking>
                <CoreTemperature>57</CoreTemperature>
            </Cooking>
        </Step>
        <Step>
            <StepType>3</StepType>
            <Duration>2400</Duration>
            <Temperature>57</Temperature>
            <HumidityPercentage>0</HumidityPercentage>
            <FanMode>3</FanMode>
            <FanSpeed>5</FanSpeed>
            <IsCoreTempStep>false</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
        </Step>
    </StepList>
</Program>
