<?xml version="1.0" encoding="UTF-8"?>
<Program Version="1.0" Stored="true">
    <ProgramType>0</ProgramType>
    <IsFavorite>false</IsFavorite>
    <MenuGroup>5</MenuGroup>
    <Image Image="Kheer (rice Pudding).JPG" ImgWide="true"/>
    <Comment></Comment>
    <PreheatActive>false</PreheatActive>
    <PreheatTemp>181.0000000000</PreheatTemp>
    <SPSActive>false</SPSActive>
    <HalfLoad>false</HalfLoad>
    <KeepWarm>false</KeepWarm>
    <ReducedHeatOutput>false</ReducedHeatOutput>
    <CleaningCoolingType>0</CleaningCoolingType>
    <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
    <CleaningStartupCheckTemp>0</CleaningStartupCheckTemp>
    <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
    <StepList>
        <Step>
            <StepType>0</StepType>
            <Duration>1200.0</Duration>
            <Temperature>165.0000000000</Temperature>
            <HumidityPercentage>20</HumidityPercentage>
            <FanMode>1</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>false</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
            <SoundAtTheEnd>false</SoundAtTheEnd>
            <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
            <Cooking>
                <CoreTemperature>0.0000000000</CoreTemperature>
            </Cooking>
            <Baking>
                <HumidityAmount>0</HumidityAmount>
                <HumidityAmountType>0</HumidityAmountType>
                <PhaseHumidityTime>0</PhaseHumidityTime>
                <PhaseRestingTime>0</PhaseRestingTime>
                <PhaseThroughTime>0</PhaseThroughTime>
            </Baking>
            <Cleaning>
                <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
                <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
                <WaterInletValveStatus>false</WaterInletValveStatus>
                <SoftWaterValveStatus>false</SoftWaterValveStatus>
                <ResetContaminationFlag>false</ResetContaminationFlag>
                <Drying2>false</Drying2>
                <IsSoaking>false</IsSoaking>
                <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
                <RecoveryPoint>false</RecoveryPoint>
            </Cleaning>
        </Step>
        <Step>
            <StepType>0</StepType>
            <Duration>1800.0</Duration>
            <Temperature>140.0000000000</Temperature>
            <HumidityPercentage>30</HumidityPercentage>
            <FanMode>1</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>false</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
            <SoundAtTheEnd>false</SoundAtTheEnd>
            <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
            <Cooking>
                <CoreTemperature>0.0000000000</CoreTemperature>
            </Cooking>
            <Baking>
                <HumidityAmount>0</HumidityAmount>
                <HumidityAmountType>0</HumidityAmountType>
                <PhaseHumidityTime>0</PhaseHumidityTime>
                <PhaseRestingTime>0</PhaseRestingTime>
                <PhaseThroughTime>0</PhaseThroughTime>
            </Baking>
            <Cleaning>
                <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
                <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
                <WaterInletValveStatus>false</WaterInletValveStatus>
                <SoftWaterValveStatus>false</SoftWaterValveStatus>
                <ResetContaminationFlag>false</ResetContaminationFlag>
                <Drying2>false</Drying2>
                <IsSoaking>false</IsSoaking>
                <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
                <RecoveryPoint>false</RecoveryPoint>
            </Cleaning>
        </Step>
        <Step>
            <StepType>2</StepType>
            <Duration>900.0</Duration>
            <Temperature>150.0000000000</Temperature>
            <HumidityPercentage>0</HumidityPercentage>
            <FanMode>1</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>false</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
            <SoundAtTheEnd>false</SoundAtTheEnd>
            <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
            <Cooking>
                <CoreTemperature>0.0000000000</CoreTemperature>
            </Cooking>
            <Baking>
                <HumidityAmount>0</HumidityAmount>
                <HumidityAmountType>0</HumidityAmountType>
                <PhaseHumidityTime>0</PhaseHumidityTime>
                <PhaseRestingTime>0</PhaseRestingTime>
                <PhaseThroughTime>0</PhaseThroughTime>
            </Baking>
            <Cleaning>
                <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
                <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
                <WaterInletValveStatus>false</WaterInletValveStatus>
                <SoftWaterValveStatus>false</SoftWaterValveStatus>
                <ResetContaminationFlag>false</ResetContaminationFlag>
                <Drying2>false</Drying2>
                <IsSoaking>false</IsSoaking>
                <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
                <RecoveryPoint>false</RecoveryPoint>
            </Cleaning>
        </Step>
    </StepList>
</Program>
