<Program Version="1.0" Stored="true">
  <ProconnectRecipeName>TK Pizza</ProconnectRecipeName>
  <RecipeIndex>0</RecipeIndex>
  <BuilderDevice>0</BuilderDevice>
  <ProgramType>1</ProgramType>
  <IsFavorite>true</IsFavorite>
  <MenuGroup>0</MenuGroup>
  <RecipeMenuGroup>0</RecipeMenuGroup>
  <RecipeProductGroup>0</RecipeProductGroup>
  <EndSoundName></EndSoundName>
  <Image Image="Pizza TK.jpg" ImgWide="false"></Image>
  <Comment>Vorheizen beachten&#xA;&#xA;Blech muss schon beim Vorheizen drinnen sein</Comment>
  <BarcodeValue></BarcodeValue>
  <RestrictValue></RestrictValue>
  <MultiDeltaT>false</MultiDeltaT>
  <PreheatActive>true</PreheatActive>
  <PreheatTemp>231.0000000000</PreheatTemp>
  <PreheatDuration>0</PreheatDuration>
  <SPSActive>false</SPSActive>
  <HalfLoad>false</HalfLoad>
  <KeepWarm>false</KeepWarm>
  <KeepWarmTemp>80.0000000000</KeepWarmTemp>
  <ReducedHeatOutput>false</ReducedHeatOutput>
  <ForceCoolAutoTemp>false</ForceCoolAutoTemp>
  <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
  <CleaningStartupCheckTemp>0.0000000000</CleaningStartupCheckTemp>
  <ResetTimeForCleaningRequest>false</ResetTimeForCleaningRequest>
  <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
  <StepList>
    <Step>
      <StepType>6</StepType>
      <Duration>540.0000000000</Duration>
      <Temperature>210.0000000000</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>4</BusFanSpeed>
      <IsCoreTempStep>false</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <ADCEnable>true</ADCEnable>
      <ADCLevel>2</ADCLevel>
      <Cooking>
        <CoreTemperature>0.0000000000</CoreTemperature>
      </Cooking>
      <Baking>
        <BakingCoreTemperature>0.0000000000</BakingCoreTemperature>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>540</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <MotorOn>false</MotorOn>
        <SteamDischarge>false</SteamDischarge>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
  </StepList>
</Program>