<?xml version="1.0" encoding="UTF-8"?>
<Program Stored="true" Version="1.0">
    <!--ProgramListConv version: 1.1. Conversion date: 2014-06-24. Done by: max.-->
    <ProgramType>0</ProgramType>
    <MenuGroup>3</MenuGroup>
    <Image Image="" ImgWide="true" />
    <StepList>
        <Step>
            <StepType>2</StepType>
            <Duration>900</Duration>
            <Temperature>235</Temperature>
            <HumidityPercentage>0</HumidityPercentage>
            <FanMode>4</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>false</IsCoreTempStep>
        </Step>
        <Step>
            <StepType>0</StepType>
            <Duration>0</Duration>
            <Temperature>200</Temperature>
            <HumidityPercentage>15</HumidityPercentage>
            <FanMode>4</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>true</IsCoreTempStep>
            <Cooking>
                <CoreTemperature>65</CoreTemperature>
            </Cooking>
        </Step>
        <Step>
            <StepType>0</StepType>
            <Duration>0</Duration>
            <Temperature>190</Temperature>
            <HumidityPercentage>5</HumidityPercentage>
            <FanMode>4</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>true</IsCoreTempStep>
            <Cooking>
                <CoreTemperature>80</CoreTemperature>
            </Cooking>
        </Step>
        <Step>
            <StepType>2</StepType>
            <Duration>0</Duration>
            <Temperature>200</Temperature>
            <HumidityPercentage>0</HumidityPercentage>
            <FanMode>4</FanMode>
            <FanSpeed>10</FanSpeed>
            <IsCoreTempStep>true</IsCoreTempStep>
            <Cooking>
                <CoreTemperature>90</CoreTemperature>
            </Cooking>
        </Step>
    </StepList>
</Program>
