<?xml version="1.0" encoding="UTF-8"?>
<Program Version="1.0" Stored="true">
    <ProconnectRecipeName>130°C - 35 Min.</ProconnectRecipeName>
    <RecipeIndex>8</RecipeIndex>
    <BuilderDevice>1</BuilderDevice>
    <ProgramType>0</ProgramType>
    <IsFavorite>false</IsFavorite>
    <MenuGroup>-1</MenuGroup>
    <Image Image="" ImgWide="true"/>
    <Comment></Comment>
    <BarcodeValue></BarcodeValue>
    <RestrictValue></RestrictValue>
    <MultiDeltaT>false</MultiDeltaT>
    <PreheatActive>false</PreheatActive>
    <PreheatTemp>143.0000000000</PreheatTemp>
    <PreheatDuration>0</PreheatDuration>
    <SPSActive>false</SPSActive>
    <HalfLoad>false</HalfLoad>
    <KeepWarm>false</KeepWarm>
    <KeepWarmTemp>50.0000000000</KeepWarmTemp>
    <ReducedHeatOutput>false</ReducedHeatOutput>
    <ForceCoolAutoTemp>false</ForceCoolAutoTemp>
    <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
    <CleaningStartupCheckTemp>0</CleaningStartupCheckTemp>
    <ResetTimeForCleaningRequest>false</ResetTimeForCleaningRequest>
    <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
    <StepList>
        <Step>
            <StepType>0</StepType>
            <Duration>2100.0</Duration>
            <Temperature>130.0000000000</Temperature>
            <HumidityPercentage>60</HumidityPercentage>
            <FanMode>1</FanMode>
            <FanSpeed>10</FanSpeed>
            <BusFanSpeed>3</BusFanSpeed>
            <IsCoreTempStep>false</IsCoreTempStep>
            <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
            <SoundAtTheEnd>false</SoundAtTheEnd>
            <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
            <Cooking>
                <CoreTemperature>0.0000000000</CoreTemperature>
            </Cooking>
            <Baking>
                <HumidityAmount>0</HumidityAmount>
                <HumidityAmountType>0</HumidityAmountType>
                <PhaseHumidityTime>0</PhaseHumidityTime>
                <PhaseRestingTime>0</PhaseRestingTime>
                <PhaseThroughTime>0</PhaseThroughTime>
            </Baking>
            <Cleaning>
                <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
                <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
                <WaterInletValveStatus>false</WaterInletValveStatus>
                <SoftWaterValveStatus>false</SoftWaterValveStatus>
                <ResetContaminationFlag>false</ResetContaminationFlag>
                <Drying2>false</Drying2>
                <IsSoaking>false</IsSoaking>
                <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
                <RecoveryPoint>false</RecoveryPoint>
                <OnlyForSoftWater>false</OnlyForSoftWater>
                <Inject2>false</Inject2>
                <DetectWaterPressure>false</DetectWaterPressure>
            </Cleaning>
        </Step>
    </StepList>
</Program>
