<?xml version="1.0" encoding="utf-8"?>
<Program Version="1.0" Stored="true">
  <ProgramType>0</ProgramType>
  <IsFavorite>false</IsFavorite>
  <MenuGroup>2</MenuGroup>
  <BuilderDevice>0</BuilderDevice>
  <Image Image="Meatloaf.jpg" ImgWide="true" />
  <BarcodeValue />
  <RestrictValue />
  <MultiDeltaT>false</MultiDeltaT>
  <PreheatActive>true</PreheatActive>
  <PreheatTemp>190.555555555556</PreheatTemp>
  <SPSActive>true</SPSActive>
  <HalfLoad>false</HalfLoad>
  <KeepWarm>false</KeepWarm>
  <ReducedHeatOutput>false</ReducedHeatOutput>
  <CleaningCoolingType>0</CleaningCoolingType>
  <SwitchOffAfterCleaning>false</SwitchOffAfterCleaning>
  <CleaningStartupCheckTemp>0.0</CleaningStartupCheckTemp>
  <OpenDoorWhenFinished>false</OpenDoorWhenFinished>
  <StepList>
    <Step>
      <StepType>0</StepType>
      <Duration>0.0</Duration>
      <Temperature>162.777777777778</Temperature>
      <HumidityPercentage>45</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>5</BusFanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>71.1111111111111</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
    <Step>
      <StepType>2</StepType>
      <Duration>0.0</Duration>
      <Temperature>162.777777777778</Temperature>
      <HumidityPercentage>0</HumidityPercentage>
      <FanMode>1</FanMode>
      <FanSpeed>10</FanSpeed>
      <BusFanSpeed>5</BusFanSpeed>
      <IsCoreTempStep>true</IsCoreTempStep>
      <ExhaustAirFlapClosed>false</ExhaustAirFlapClosed>
      <SoundAtTheEnd>false</SoundAtTheEnd>
      <WaitDoorOpenAtTheEnd>false</WaitDoorOpenAtTheEnd>
      <Cooking>
        <CoreTemperature>73.8888888888889</CoreTemperature>
      </Cooking>
      <Baking>
        <HumidityAmount>0</HumidityAmount>
        <HumidityAmountType>0</HumidityAmountType>
        <PhaseHumidityTime>0</PhaseHumidityTime>
        <PhaseRestingTime>0</PhaseRestingTime>
        <PhaseThroughTime>0</PhaseThroughTime>
      </Baking>
      <Cleaning>
        <CleaningAgentPumpStatus>false</CleaningAgentPumpStatus>
        <RinseAgentPumpStatus>false</RinseAgentPumpStatus>
        <WaterInletValveStatus>false</WaterInletValveStatus>
        <SoftWaterValveStatus>false</SoftWaterValveStatus>
        <ResetContaminationFlag>false</ResetContaminationFlag>
        <Drying2>false</Drying2>
        <IsSoaking>false</IsSoaking>
        <OnlyFor2ChamberDevices>false</OnlyFor2ChamberDevices>
        <RecoveryPoint>false</RecoveryPoint>
        <OnlyForSoftWater>false</OnlyForSoftWater>
        <Inject2>false</Inject2>
        <DetectWaterPressure>false</DetectWaterPressure>
      </Cleaning>
    </Step>
  </StepList>
  <Comment>INSERT PROBE 

</Comment>
</Program>